/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package bug

class App {
    String getGreeting() {
        return 'Hello World!'
    }

    static void main(String[] args) {
        println new App().greeting

        SomeClass sc = new SomeClass()
        println sc.getVal()
    }

    static class SomeClass implements SomeInterface {
        int getVal() {
            // return SOME_VAL
            return ANOTHER_VAL
        }
    }
}
